# Generated by Django 3.2.8 on 2021-10-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classname',
        ),
        migrations.AddField(
            model_name='user',
            name='classname',
            field=models.ManyToManyField(to='main.MeetUrl'),
        ),
    ]
