# Generated by Django 3.2.8 on 2021-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_meeturl_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='timeListened',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
