# Generated by Django 3.2.8 on 2021-10-28 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_timings_timelistened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='timeListened',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
